### ISSUE TITLE
还没开始写吗

### ISSUE THREAD

**Issue by mushanzi1216** [edagarli/Nicole#1]
怎么只有依赖 是过年放假回家了吗

**Comment by edagarli** [comment]
初步简单的架构已经OKAY了。也加入了AOP支持。打个jar就可以了。

之后我会写个使用文档。具体框架的一些设计文档。

谢谢你的关注。

**Comment by edagarli** [comment]
pom文件我已经更新了。是少了一些核心的依赖包。

**Comment by mushanzi1216** [comment]
过年好 为什么用jsp呢  不用velicity 另外前端会采用什么框架吗

**Comment by edagarli** [comment]
你提的很对～  
客户端目前可使用 HTML 或 JSP 作为视图模板  
我最近在考虑支持velicity
前端个人倾向于AugularJs设计思想

**Comment by mushanzi1216** [comment]
方便加微信吗 15101668620 加完我会删除这条记录

**Comment by edagarli** [comment]
微信不太常上，我一般telegram常在线，可加用户: edagarli

**Comment by mushanzi1216** [comment]
这样好吗  我没用 但是听过大名鼎鼎 俄国毛子搞出来的

**Comment by edagarli** [comment]
一直在用，推荐～

**Comment by mushanzi1216** [comment]
已联系到你

**Comment by edagarli** [comment]
赞～
